# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "88d7109d17f7991376bb4d5d8629eee1"
name = "RecoSys"
handle = "recosys-1"
application_url = "https://housewares-ralph-jill-cosmetic.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://housewares-ralph-jill-cosmetic.trycloudflare.com/auth/callback",
  "https://housewares-ralph-jill-cosmetic.trycloudflare.com/auth/shopify/callback",
  "https://housewares-ralph-jill-cosmetic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "recosystest.myshopify.com"
automatically_update_urls_on_dev = true
